name: Deploy Pages

on:
  push:
    branches: [main]  # 只在 main 分支推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取所有历史以便 Vitepress 能生成正确的 lastUpdated 时间

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 使用 Node.js 20 (Vitepress 支持的版本)
          cache: 'npm'       # 如果你使用 pnpm，可以缓存它

      - name: Install dependencies
        run: |
          npm install         # 或者使用 pnpm install / yarn install

      - name: Build Vitepress
        run: npm run docs:build   # 假设你的构建命令是 "docs:build"，根据你的实际情况调整

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist  # Vitepress 默认输出目录